/* Generated By:JavaCC: Do not edit this line. Linguagem20252.java */
package app;

import java.io.InputStream;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import static app.Linguagem20252Constants.*;

public class Linguagem20252 implements Linguagem20252Constants {

    public static int errosSintaticosCount = 0;
    public static int errosLexicosCount = 0;
    public static StringBuilder errosSintaticos = new StringBuilder();

    public String getListaTokensEsperados(int[][] conjuntoDeTokensEsperados){
        StringBuilder listaTokens = new StringBuilder();
        for (int[] conjunto : conjuntoDeTokensEsperados){
            for (int token : conjunto){
                String descricao = OutputDictionary.getCategory(token);

                if (descricao.isEmpty()) {
                    descricao = tokenImage[token];
                }
                listaTokens.append(descricao).append(" ");
            }
        }
        return listaTokens.toString().trim();
    }

    public static java.util.ArrayList analiseLexica(InputStream input) throws ParseException {
            errosLexicosCount = 0;
            Linguagem20252 lexer = new Linguagem20252(input);
            java.util.ArrayList tokens = new java.util.ArrayList();
            Token token;
            do {
                token = lexer.getNextToken();
                if(token.kind == Linguagem20252Constants.MALFORMED_IDENTIFIER
                    || token.kind == Linguagem20252Constants.MALFORMED_NUMBER
                    || token.kind == Linguagem20252Constants.MALFORMED_REAL
                    || token.kind == Linguagem20252Constants.INVALID_SIMBOL
                    || token.kind == Linguagem20252Constants.UNCLOSED_QUOTE
                    || token.kind == Linguagem20252Constants.UNCLOSED_STRING
                    || token.kind == Linguagem20252Constants.UNCLOSED_BLOCK_COMMENT){
                    tokens.add(token);
                    errosLexicosCount++;
                }
            } while (token.kind != Linguagem20252Constants.EOF);

            return tokens;
        }

    public static StringBuilder analiseSintatica(InputStream input) throws ParseException {
            Linguagem20252 parser = new Linguagem20252(input);
            errosSintaticosCount = 0;
            errosSintaticos = new StringBuilder();
            parser.Programa();
            return errosSintaticos;
    }

    public Token skipToSynchronizingToken(int... synchronizingKinds) {
        Token t = getToken(1);

        while (t.kind != EOF && !isSynchronizingToken(t, synchronizingKinds)) {
            t = getNextToken();
        }

        return getToken(1);
    }

    private static boolean isSynchronizingToken(Token t, int... synchronizingKinds) {
        for (int kind : synchronizingKinds) {
            if (t.kind == kind) return true;
        }
        return false;
    }

    boolean isEOF() {
        return getToken(1).kind == EOF;
    }

// # PROGRAMA
  final public void Programa() throws ParseException {
    try {
      jj_consume_token(BEGIN);
      NomeDoPrograma();
      BlocoDefine();
      BlocoStart();
      BlocoEnd();
    } catch (ParseException e) {
        errosSintaticosCount++;
        String tokensEsperados = getListaTokensEsperados(e.expectedTokenSequences);

        TokenStringBuilder.formatErroSintaticoToString(e, errosSintaticos, tokensEsperados);

        if (tokensEsperados.contains("begin")){
            errosSintaticos.append("Erro sint\u00e1tico: Programa deve iniciar com 'BEGIN'").append("\n\n");
        }
        Token t = getToken(1);
        if (t.kind == EOF){
            errosSintaticos.append("Erro sint\u00e1tico: Fim inesperado do programa.").append("\n\n");
        }
        // RECUPERAÇÃO DE ERROS
        skipToSynchronizingToken(END, START, DEFINE);
        t = getToken(1);
        if (t.kind == END){
            BlocoEnd();
        }else if (t.kind == START){
            BlocoStart(); BlocoEnd(); // talvez try catch em cada um, acho que nao
        }else if (t.kind == DEFINE){
            BlocoDefine(); BlocoStart(); BlocoEnd();
        }
    }
  }

  final public void NomeDoPrograma() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case IDENTIFIER:
      jj_consume_token(IDENTIFIER);
      break;
    default:
      jj_la1[0] = jj_gen;
      ;
    }
  }

  final public void BlocoDefine() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case DEFINE:
      jj_consume_token(DEFINE);
      ListaDeVariaveis();
      break;
    default:
      jj_la1[1] = jj_gen;
      ;
    }
  }

  final public void BlocoStart() throws ParseException {
    try {
      jj_consume_token(START);
      ListaDeComandos();
    } catch (ParseException e) {
        if(isEOF()){{if (true) throw e;}}

        errosSintaticosCount++;
        String tokensEsperados = getListaTokensEsperados(e.expectedTokenSequences);

        TokenStringBuilder.formatErroSintaticoToString(e, errosSintaticos, tokensEsperados);

        if (tokensEsperados.contains("start")){
            errosSintaticos.append("Erro sint\u00e1tico: Se\u00e7\u00e3o de comandos deve iniciar com 'START'").append("\n\n");
        }

        skipToSynchronizingToken(SET, READ, SHOW, IF, LOOP, END);
        Token t = getToken(1);
        if (t.kind != END){ // se achar END, desempilha
            ListaDeComandos() /* semantica*/; // talvez try catch? nao acho que precisa
        }
    }
  }

  final public void BlocoEnd() throws ParseException {
    try {
      jj_consume_token(END);
      jj_consume_token(DOT);
    } catch (ParseException e) {
        errosSintaticosCount++;
        String tokensEsperados = getListaTokensEsperados(e.expectedTokenSequences);

        TokenStringBuilder.formatErroSintaticoToString(e, errosSintaticos, tokensEsperados);

        if (tokensEsperados.contains("end") || tokensEsperados.contains("DOT")) {
            errosSintaticos.append("Erro sint\u00e1tico: Programa deve acabar com 'END.'").append("\n\n");
        }
    }
  }

// DECLARACOES
  final public void ListaDeVariaveis() throws ParseException {
    Variavel();
    ListaDeVariaveisAux();
  }

  final public void ListaDeVariaveisAux() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case IDENTIFIER:
      Variavel();
      ListaDeVariaveisAux();
      break;
    default:
      jj_la1[2] = jj_gen;
      ;
    }
  }

  final public void Variavel() throws ParseException {
    try {
      ListaIdentificadores();
      jj_consume_token(COLON);
      Tipo();
      DeclaracaoArray();
      jj_consume_token(SEMICOLON);
    } catch (ParseException e) {
        if(isEOF()){{if (true) throw e;}}

        Token t = getToken(1);
        if(t.kind != START && t.kind != IDENTIFIER && t.kind != EOF){
            errosSintaticosCount++;
            String tokensEsperados = getListaTokensEsperados(e.expectedTokenSequences);

            TokenStringBuilder.formatErroSintaticoToString(e, errosSintaticos, tokensEsperados);

            if(tokensEsperados.contains(":")){
                 errosSintaticos.append("Erro sint\u00e1tico: Declara\u00e7\u00e3o de vari\u00e1vel deve conter ':' ap\u00f3s a lista de vari\u00e1veis").append("\n\n");
            }else if(tokensEsperados.contains(";")){
                errosSintaticos.append("Erro sint\u00e1tico: Declara\u00e7\u00e3o da vari\u00e1vel deve terminar com ';' ap\u00f3s especifica\u00e7\u00e3o do tipo").append("\n\n");
            }
            skipToSynchronizingToken(IDENTIFIER, START);
        }
    }
  }

  final public void ListaIdentificadores() throws ParseException {
    try {
      jj_consume_token(IDENTIFIER);
      ListaIdentificadoresAux();
    } catch (ParseException e) {
        if(isEOF()){{if (true) throw e;}}

        errosSintaticosCount++;
        String tokensEsperados = getListaTokensEsperados(e.expectedTokenSequences);

        TokenStringBuilder.formatErroSintaticoToString(e, errosSintaticos, tokensEsperados);
        errosSintaticos.append("Erro sint\u00e1tico: O bloco 'Define' deve conter ao menos uma declara\u00e7\u00e3o de vari\u00e1vel (identificador : tipo ;)").append("\n\n");

        skipToSynchronizingToken(START, COLON, IDENTIFIER);
    }
  }

  final public void ListaIdentificadoresAux() throws ParseException {
    try {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case COMMA:
        jj_consume_token(COMMA);
        jj_consume_token(IDENTIFIER);
        ListaIdentificadoresAux();
        break;
      default:
        jj_la1[3] = jj_gen;
        ;
      }
    } catch (ParseException e) {
        if(isEOF()){{if (true) throw e;}}

        errosSintaticosCount++;
        String tokensEsperados = getListaTokensEsperados(e.expectedTokenSequences);

        TokenStringBuilder.formatErroSintaticoToString(e, errosSintaticos, tokensEsperados);

        if(tokensEsperados.contains(",")){
             errosSintaticos.append("Erro sint\u00e1tico: Elementos declarados devem estar separados por ','").append("\n\n");
        }else if(tokensEsperados.contains("identificador")){
            errosSintaticos.append("Erro sint\u00e1tico: Deve conter ao menos um 'Identificador' ap\u00f3s a ','").append("\n\n");
        }
        skipToSynchronizingToken(COMMA, START, COLON, IDENTIFIER);

        Token t = getToken(1);
        if(t.kind == COMMA){
            ListaIdentificadoresAux();
        }
    }
  }

  final public void Tipo() throws ParseException {
    try {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case TYPE_NUM:
        jj_consume_token(TYPE_NUM);
        break;
      case TYPE_REAL:
        jj_consume_token(TYPE_REAL);
        break;
      case TYPE_TEXT:
        jj_consume_token(TYPE_TEXT);
        break;
      case TYPE_FLAG:
        jj_consume_token(TYPE_FLAG);
        break;
      default:
        jj_la1[4] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    } catch (ParseException e) {
        if(isEOF()){{if (true) throw e;}}

        errosSintaticosCount++;
        String tokensEsperados = getListaTokensEsperados(e.expectedTokenSequences);

        TokenStringBuilder.formatErroSintaticoToString(e, errosSintaticos, tokensEsperados);

        if(tokensEsperados.contains("numero inteiro") || tokensEsperados.contains("numero real") || tokensEsperados.contains("texto") || tokensEsperados.contains("constante logica")){
             errosSintaticos.append("Erro sint\u00e1tico: Tipo declarado deve pertencer ao conjunto: {'NUM', 'REAL', 'TEXT', 'TRUE', 'FALSE'}").append("\n\n");
        }
        Token t = skipToSynchronizingToken(LBRACKET, START, IDENTIFIER);

        if(t.kind == IDENTIFIER | t.kind == START){
            {if (true) throw new ParseException("Sincronizado com identificador ou start dentro de Tipo()");}
        }
    }
  }

  final public void DeclaracaoArray() throws ParseException {
    try {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case LBRACKET:
        jj_consume_token(LBRACKET);
        jj_consume_token(NUMBER);
        jj_consume_token(RBRACKET);
        DeclaracaoValoresArray();
        break;
      default:
        jj_la1[5] = jj_gen;
        DeclaracaoValoresEscalar();
      }
    } catch (ParseException e) {
        if(isEOF()){{if (true) throw e;}}

        errosSintaticosCount++;
        String tokensEsperados = getListaTokensEsperados(e.expectedTokenSequences);

        TokenStringBuilder.formatErroSintaticoToString(e, errosSintaticos, tokensEsperados);

        if(tokensEsperados.contains("[") || tokensEsperados.contains("]")){
            errosSintaticos.append("Erro sint\u00e1tico: Declara\u00e7\u00e3o de tamanho do array deve ser feita entre '[' e ']'").append("\n\n");
        }
        // else aqui para <number>?
        skipToSynchronizingToken(IDENTIFIER, START, ASSIGN);

        Token t = getToken(1);
        if(t.kind == ASSIGN) {
            DeclaracaoValoresArray() /* semantica*/;
        }
    }
  }

  final public void DeclaracaoValoresArray() throws ParseException {
    try {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case ASSIGN:
        jj_consume_token(ASSIGN);
        jj_consume_token(LBRACE);
        ListaDeValoresVetor();
        jj_consume_token(RBRACE);
        break;
      default:
        jj_la1[6] = jj_gen;
        ;
      }
    } catch (ParseException e) {
        if(isEOF()){{if (true) throw e;}}

        errosSintaticosCount++;
        String tokensEsperados = getListaTokensEsperados(e.expectedTokenSequences);

        TokenStringBuilder.formatErroSintaticoToString(e, errosSintaticos, tokensEsperados);

        if(tokensEsperados.contains("=")){
            errosSintaticos.append("Erro sint\u00e1tico: Atribui\u00e7\u00f5es devem ser feitas a partir do simbolo '='").append("\n\n");
        }
        if(tokensEsperados.contains("{") || tokensEsperados.contains("}")){
            errosSintaticos.append("Erro sint\u00e1tico: Declara\u00e7\u00f5es de valores dentro de arrays devem ser feitas entre '{' e '}'").append("\n\n");
        }
        skipToSynchronizingToken(START, IDENTIFIER);
    }
  }

  final public void DeclaracaoValoresEscalar() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case ASSIGN:
      jj_consume_token(ASSIGN);
      Valor();
      break;
    default:
      jj_la1[7] = jj_gen;
      ;
    }
  }

  final public void ListaDeValoresVetor() throws ParseException {
    Valor();
    ListaDeValoresVetorAux();
  }

  final public void ListaDeValoresVetorAux() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case COMMA:
      jj_consume_token(COMMA);
      Valor();
      ListaDeValoresVetorAux();
      break;
    default:
      jj_la1[8] = jj_gen;
      ;
    }
  }

  final public void Valor() throws ParseException {
    try {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case NUMBER:
        jj_consume_token(NUMBER);
        break;
      case REAL:
        jj_consume_token(REAL);
        break;
      case TEXT_DOUBLE:
        jj_consume_token(TEXT_DOUBLE);
        break;
      case TEXT_SINGLE:
        jj_consume_token(TEXT_SINGLE);
        break;
      case TRUE:
        jj_consume_token(TRUE);
        break;
      case FALSE:
        jj_consume_token(FALSE);
        break;
      default:
        jj_la1[9] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    } catch (ParseException e) {
        if(isEOF()){{if (true) throw e;}}

        errosSintaticosCount++;
        String tokensEsperados = getListaTokensEsperados(e.expectedTokenSequences);

        TokenStringBuilder.formatErroSintaticoToString(e, errosSintaticos, tokensEsperados);

        if (tokensEsperados.contains("numero inteiro") || tokensEsperados.contains("numero real") || tokensEsperados.contains("texto")
           || tokensEsperados.contains("constante logica"))
        {
            errosSintaticos.append("Erro sint\u00e1tico: Elemento deve pertencer ao conjunto: {'Constante num\u00e9rica', 'Constante num\u00e9rica real', 'Constante literal', 'TRUE' ou 'FALSE'}").append("\n\n");
        }
        skipToSynchronizingToken(COMMA, START, IDENTIFIER);
    }
  }

// COMANDOS
  final public void ListaDeComandos() throws ParseException {
    Comando();
    ListaDeComandosAux();
  }

  final public void ListaDeComandosAux() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case SET:
    case READ:
    case SHOW:
    case IF:
    case LOOP:
      Comando();
      ListaDeComandosAux();
      break;
    default:
      jj_la1[10] = jj_gen;
      ;
    }
  }

  final public void Comando() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case SET:
      Atribuicao();
      break;
    case READ:
      EntradaDeDados();
      break;
    case SHOW:
      SaidaDeDados();
      break;
    case IF:
      Selecao();
      break;
    case LOOP:
      Repeticao();
      break;
    default:
      jj_la1[11] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  final public void Atribuicao() throws ParseException {
    try {
      jj_consume_token(SET);
      jj_consume_token(IDENTIFIER);
      Indice();
      jj_consume_token(ASSIGN);
      Expressao();
      jj_consume_token(SEMICOLON);
    } catch (ParseException e) {
        if(isEOF()){{if (true) throw e;}}

        errosSintaticosCount++;
        String tokensEsperados = getListaTokensEsperados(e.expectedTokenSequences);

        TokenStringBuilder.formatErroSintaticoToString(e, errosSintaticos, tokensEsperados);

        errosSintaticos.append("Erro sint\u00e1tico: Comando de atribui\u00e7\u00e3o deve seguir a sintaxe: 'set identificador[indice]/identificador = (valor ou express\u00e3o);'").append("\n\n");

        skipToSynchronizingToken(SET, READ, SHOW, IF, LOOP);
    }
  }

  final public void Indice() throws ParseException {
    try {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case LBRACKET:
        jj_consume_token(LBRACKET);
        Expressao();
        jj_consume_token(RBRACKET);
        break;
      default:
        jj_la1[12] = jj_gen;
        ;
      }
    } catch (ParseException e) {
        if(isEOF()){{if (true) throw e;}}

        errosSintaticosCount++;
        String tokensEsperados = getListaTokensEsperados(e.expectedTokenSequences);

        TokenStringBuilder.formatErroSintaticoToString(e, errosSintaticos, tokensEsperados);

        errosSintaticos.append("Erro sint\u00e1tico: Indice deve estar entre '[' e ']'").append("\n\n");

        skipToSynchronizingToken(SET, READ, SHOW, IF, LOOP);
    }
  }

  final public void EntradaDeDados() throws ParseException {
    try {
      jj_consume_token(READ);
      jj_consume_token(LPAREN);
      jj_consume_token(IDENTIFIER);
      Indice();
      jj_consume_token(RPAREN);
      jj_consume_token(SEMICOLON);
    } catch (ParseException e) {
        if(isEOF()){{if (true) throw e;}}
        errosSintaticosCount++;

        String tokensEsperados = getListaTokensEsperados(e.expectedTokenSequences);

        TokenStringBuilder.formatErroSintaticoToString(e, errosSintaticos, tokensEsperados);

        errosSintaticos.append("Erro sint\u00e1tico: Comando de entrada de dados deve seguir a sintaxe: 'READ(identificador/identificador[indice]);'").append("\n\n");

        skipToSynchronizingToken(SET, READ, SHOW, IF, LOOP);
    }
  }

  final public void SaidaDeDados() throws ParseException {
    try {
      jj_consume_token(SHOW);
      jj_consume_token(LPAREN);
      ListaDeSaida();
      jj_consume_token(RPAREN);
      jj_consume_token(SEMICOLON);
    } catch (ParseException e) {
        if(isEOF()){{if (true) throw e;}}
        errosSintaticosCount++;

        String tokensEsperados = getListaTokensEsperados(e.expectedTokenSequences);

        TokenStringBuilder.formatErroSintaticoToString(e, errosSintaticos, tokensEsperados);

        errosSintaticos.append("Erro Sintatico: Comando de saida de dados deve seguir a sintaxe: 'SHOW(identificador/identificador[indice]);' ou\n\t 'SHOW(valor/valor,valor)'").append("\n\n");

        skipToSynchronizingToken(SET, READ, SHOW, IF, LOOP);
    }
  }

  final public void ListaDeSaida() throws ParseException {
    Item();
    ListaDeSaidaAux();
  }

  final public void ListaDeSaidaAux() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case COMMA:
      jj_consume_token(COMMA);
      Item();
      ListaDeSaidaAux();
      break;
    default:
      jj_la1[13] = jj_gen;
      ;
    }
  }

  final public void Item() throws ParseException {
    try {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case IDENTIFIER:
        jj_consume_token(IDENTIFIER);
        Indice();
        break;
      case NUMBER:
        jj_consume_token(NUMBER);
        break;
      case REAL:
        jj_consume_token(REAL);
        break;
      case TEXT_DOUBLE:
        jj_consume_token(TEXT_DOUBLE);
        break;
      case TEXT_SINGLE:
        jj_consume_token(TEXT_SINGLE);
        break;
      default:
        jj_la1[14] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    } catch (ParseException e) {
        if(isEOF()){{if (true) throw e;}}
        errosSintaticosCount++;

        String tokensEsperados = getListaTokensEsperados(e.expectedTokenSequences);

        TokenStringBuilder.formatErroSintaticoToString(e, errosSintaticos, tokensEsperados);

        skipToSynchronizingToken(SET, READ, SHOW, IF, LOOP, COMMA, RPAREN);
    }
  }

  final public void Selecao() throws ParseException {
    try {
      jj_consume_token(IF);
      Expressao();
      jj_consume_token(THEN);
      ListaDeComandos();
      Else();
      jj_consume_token(END);
      jj_consume_token(SEMICOLON);
    } catch (ParseException e) {
        if(isEOF()){{if (true) throw e;}}
        errosSintaticosCount++;

        String tokensEsperados = getListaTokensEsperados(e.expectedTokenSequences);

        TokenStringBuilder.formatErroSintaticoToString(e, errosSintaticos, tokensEsperados);

        errosSintaticos.append("Erro sint\u00e1tico: Comando de sele\u00e7\u00e3o deve seguir a sintaxe: 'IF <condi\u00e7\u00e3o> THEN <comandos> END'").append("\n\n");

        skipToSynchronizingToken(SET, READ, SHOW, IF, LOOP);
    }
  }

  final public void Else() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case ELSE:
      jj_consume_token(ELSE);
      ListaDeComandos();
      break;
    default:
      jj_la1[15] = jj_gen;
      ;
    }
  }

  final public void Repeticao() throws ParseException {
    try {
      jj_consume_token(LOOP);
      jj_consume_token(WHILE);
      Expressao();
      ListaDeComandos();
      jj_consume_token(END);
      jj_consume_token(SEMICOLON);
    } catch (ParseException e) {
        if(isEOF()){{if (true) throw e;}}
        errosSintaticosCount++;

        String tokensEsperados = getListaTokensEsperados(e.expectedTokenSequences);

        TokenStringBuilder.formatErroSintaticoToString(e, errosSintaticos, tokensEsperados);

        if(tokensEsperados.contains("loop") || tokensEsperados.contains("while") || tokensEsperados.contains("end")){
            errosSintaticos.append("Erro sint\u00e1tico: Comando de repeti\u00e7\u00e3o devem a sintaxe: 'LOOP WHILE <comandos> END").append("\n\n");
        }
        skipToSynchronizingToken(SET, READ, SHOW, IF, LOOP);
    }
  }

// EXPRESSAO
  final public void Expressao() throws ParseException {
    ExpressaoAritmeticaOuLogica();
    ExpressaoAux();
  }

  final public void ExpressaoAux() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case EQUAL:
    case NOT_EQUAL:
    case SHIFT_LEFT:
    case SHIFT_RIGHT:
    case SHIFT_LEFT_ASSIGN:
    case SHIFT_RIGHT_ASSIGN:
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case EQUAL:
        jj_consume_token(EQUAL);
        ExpressaoAritmeticaOuLogica();
        break;
      case NOT_EQUAL:
        jj_consume_token(NOT_EQUAL);
        ExpressaoAritmeticaOuLogica();
        break;
      case SHIFT_LEFT:
        jj_consume_token(SHIFT_LEFT);
        ExpressaoAritmeticaOuLogica();
        break;
      case SHIFT_RIGHT:
        jj_consume_token(SHIFT_RIGHT);
        ExpressaoAritmeticaOuLogica();
        break;
      case SHIFT_LEFT_ASSIGN:
        jj_consume_token(SHIFT_LEFT_ASSIGN);
        ExpressaoAritmeticaOuLogica();
        break;
      case SHIFT_RIGHT_ASSIGN:
        jj_consume_token(SHIFT_RIGHT_ASSIGN);
        ExpressaoAritmeticaOuLogica();
        break;
      default:
        jj_la1[16] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      break;
    default:
      jj_la1[17] = jj_gen;
      ;
    }
  }

  final public void ExpressaoAritmeticaOuLogica() throws ParseException {
    Termo2();
    MenorPrioridade();
  }

  final public void MenorPrioridade() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case PLUS:
    case MINUS:
    case PIPE:
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case PLUS:
        jj_consume_token(PLUS);
        Termo2();
        MenorPrioridade();
        break;
      case MINUS:
        jj_consume_token(MINUS);
        Termo2();
        MenorPrioridade();
        break;
      case PIPE:
        jj_consume_token(PIPE);
        Termo2();
        MenorPrioridade();
        break;
      default:
        jj_la1[18] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      break;
    default:
      jj_la1[19] = jj_gen;
      ;
    }
  }

  final public void Termo2() throws ParseException {
    Termo1();
    MediaPrioridade();
  }

  final public void MediaPrioridade() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case STAR:
    case SLASH:
    case PERCENT:
    case DOUBLE_PERCENT:
    case AMPERSAND:
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case STAR:
        jj_consume_token(STAR);
        Termo1();
        MediaPrioridade();
        break;
      case SLASH:
        jj_consume_token(SLASH);
        Termo1();
        MediaPrioridade();
        break;
      case PERCENT:
        jj_consume_token(PERCENT);
        Termo1();
        MediaPrioridade();
        break;
      case DOUBLE_PERCENT:
        jj_consume_token(DOUBLE_PERCENT);
        Termo1();
        MediaPrioridade();
        break;
      case AMPERSAND:
        jj_consume_token(AMPERSAND);
        Termo1();
        MediaPrioridade();
        break;
      default:
        jj_la1[20] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      break;
    default:
      jj_la1[21] = jj_gen;
      ;
    }
  }

  final public void Termo1() throws ParseException {
    Elemento();
    MaiorPrioridade();
  }

  final public void MaiorPrioridade() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case POWER:
      jj_consume_token(POWER);
      Elemento();
      MaiorPrioridade();
      break;
    default:
      jj_la1[22] = jj_gen;
      ;
    }
  }

  final public void Elemento() throws ParseException {
    try {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case IDENTIFIER:
        jj_consume_token(IDENTIFIER);
        Indice();
        break;
      case NUMBER:
        jj_consume_token(NUMBER);
        break;
      case REAL:
        jj_consume_token(REAL);
        break;
      case TEXT_DOUBLE:
        jj_consume_token(TEXT_DOUBLE);
        break;
      case TEXT_SINGLE:
        jj_consume_token(TEXT_SINGLE);
        break;
      case TRUE:
        jj_consume_token(TRUE);
        break;
      case FALSE:
        jj_consume_token(FALSE);
        break;
      case LPAREN:
        jj_consume_token(LPAREN);
        Expressao();
        jj_consume_token(RPAREN);
        break;
      case EXCLAMATION:
        jj_consume_token(EXCLAMATION);
        jj_consume_token(LPAREN);
        Expressao();
        jj_consume_token(RPAREN);
        break;
      default:
        jj_la1[23] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    } catch (ParseException e) {
        if(isEOF()){{if (true) throw e;}}

        errosSintaticosCount++;
        String tokensEsperados = getListaTokensEsperados(e.expectedTokenSequences);

        TokenStringBuilder.formatErroSintaticoToString(e, errosSintaticos, tokensEsperados);

        if (tokensEsperados.contains("identificador") || tokensEsperados.contains("numero inteiro") || tokensEsperados.contains("numero real") || tokensEsperados.contains("texto")
           || tokensEsperados.contains("constante logica"))
        {
            errosSintaticos.append("Erro sint\u00e1tico: Elemento deve pertencer ao conjunto: {'Identificador', 'Constante num\u00e9rica', 'Constante num\u00e9rica real', 'Constante literal', 'TRUE' ou 'FALSE'}").append("\n\n");
        }else if (tokensEsperados.contains("(") || tokensEsperados.contains(")")){
            errosSintaticos.append("Erro sint\u00e1tico: Elemento deve estar entre '(' e ')'").append("\n\n");
        }else if (tokensEsperados.contains("!")){
            errosSintaticos.append("Erro sint\u00e1tico: Elemento deve estar entre '!(' e ')'").append("\n\n");
        }
        skipToSynchronizingToken(RPAREN, RBRACKET, SET, READ, SHOW, IF, LOOP, THEN, SEMICOLON);
    }
  }

  /** Generated Token Manager. */
  public Linguagem20252TokenManager token_source;
  SimpleCharStream jj_input_stream;
  /** Current token. */
  public Token token;
  /** Next token. */
  public Token jj_nt;
  private int jj_ntk;
  private int jj_gen;
  final private int[] jj_la1 = new int[24];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static {
      jj_la1_init_0();
      jj_la1_init_1();
   }
   private static void jj_la1_init_0() {
      jj_la1_0 = new int[] {0x0,0x0,0x0,0x200000,0x0,0x2000000,0x10000,0x10000,0x200000,0x1d00,0x0,0x0,0x2000000,0x200000,0x1d00,0x0,0x60000,0x60000,0x60000000,0x60000000,0x80000000,0x80000000,0x0,0x8001d00,};
   }
   private static void jj_la1_init_1() {
      jj_la1_1 = new int[] {0x40000000,0x10000,0x40000000,0x0,0x7800,0x0,0x0,0x0,0x0,0x18000000,0x2780000,0x2780000,0x0,0x0,0x40000000,0x1000000,0xf0,0xf0,0x200,0x200,0x40b,0x40b,0x4,0x58000100,};
   }

  /** Constructor with InputStream. */
  public Linguagem20252(java.io.InputStream stream) {
     this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public Linguagem20252(java.io.InputStream stream, String encoding) {
    try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source = new Linguagem20252TokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 24; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream) {
     ReInit(stream, null);
  }
  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream, String encoding) {
    try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 24; i++) jj_la1[i] = -1;
  }

  /** Constructor. */
  public Linguagem20252(java.io.Reader stream) {
    jj_input_stream = new SimpleCharStream(stream, 1, 1);
    token_source = new Linguagem20252TokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 24; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(java.io.Reader stream) {
    jj_input_stream.ReInit(stream, 1, 1);
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 24; i++) jj_la1[i] = -1;
  }

  /** Constructor with generated Token Manager. */
  public Linguagem20252(Linguagem20252TokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 24; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(Linguagem20252TokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 24; i++) jj_la1[i] = -1;
  }

  private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }


/** Get the next Token. */
  final public Token getNextToken() {
    if (token.next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    jj_gen++;
    return token;
  }

/** Get the specific Token. */
  final public Token getToken(int index) {
    Token t = token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) t = t.next;
      else t = t.next = token_source.getNextToken();
    }
    return t;
  }

  private int jj_ntk() {
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  private java.util.List jj_expentries = new java.util.ArrayList();
  private int[] jj_expentry;
  private int jj_kind = -1;

  /** Generate ParseException. */
  public ParseException generateParseException() {
    jj_expentries.clear();
    boolean[] la1tokens = new boolean[64];
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 24; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
          if ((jj_la1_1[i] & (1<<j)) != 0) {
            la1tokens[32+j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 64; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.add(jj_expentry);
      }
    }
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = (int[])jj_expentries.get(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  /** Enable tracing. */
  final public void enable_tracing() {
  }

  /** Disable tracing. */
  final public void disable_tracing() {
  }

}
