/* Generated By:JavaCC: Do not edit this line. Linguagem20252.java */
package app;

import java.io.InputStream;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import static app.Linguagem20252Constants.*;

public class Linguagem20252 implements Linguagem20252Constants {

    public static int errosSintaticosCount = 0;
    public static int errosLexicosCount = 0;
    public static StringBuilder errosSintaticos = new StringBuilder();

    public String getListaTokensEsperados(int[][] conjuntoDeTokensEsperados){
        StringBuilder listaTokens = new StringBuilder();
        for (int[] conjunto : conjuntoDeTokensEsperados){
            for (int token : conjunto){
                listaTokens.append(tokenImage[token]).append(" ");
            }
        }
        return listaTokens.toString().trim();
    }

    public static java.util.ArrayList analiseLexica(InputStream input) throws ParseException {
            errosLexicosCount = 0;
            Linguagem20252 lexer = new Linguagem20252(input);
            java.util.ArrayList tokens = new java.util.ArrayList();
            Token token;
            do {
                token = lexer.getNextToken();
                if(token.kind == Linguagem20252Constants.MALFORMED_IDENTIFIER
                    || token.kind == Linguagem20252Constants.MALFORMED_NUMBER
                    || token.kind == Linguagem20252Constants.MALFORMED_REAL
                    || token.kind == Linguagem20252Constants.INVALID_SIMBOL
                    || token.kind == Linguagem20252Constants.UNCLOSED_QUOTE
                    || token.kind == Linguagem20252Constants.UNCLOSED_STRING
                    || token.kind == Linguagem20252Constants.UNCLOSED_BLOCK_COMMENT){
                    tokens.add(token);
                    errosLexicosCount++;
                }
            } while (token.kind != Linguagem20252Constants.EOF);

            return tokens;
        }

    public static StringBuilder analiseSintatica(InputStream input) throws ParseException {
            Linguagem20252 parser = new Linguagem20252(input);
            errosSintaticosCount = 0;
            errosSintaticos = new StringBuilder();
            parser.Programa();
            return errosSintaticos;
    }

    public Token skipToSynchronizingToken(int... synchronizingKinds) {
        Token t = getToken(0);

        while (t.kind != EOF && !isSynchronizingToken(t, synchronizingKinds)) {
            t = getNextToken();
        }

        return t;
    }

    private static boolean isSynchronizingToken(Token t, int... synchronizingKinds) {
        for (int kind : synchronizingKinds) {
            if (t.kind == kind) return true;
        }
        return false;
    }

  final public void Programa() throws ParseException {
    try {
      jj_consume_token(BEGIN);
      NomeDoPrograma();
      BlocoDefine();
      jj_consume_token(START);
      ListaDeComandos();
      jj_consume_token(END);
      jj_consume_token(DOT);
    } catch (ParseException e) {
        errosSintaticosCount++;
        String tokensEsperados = getListaTokensEsperados(e.expectedTokenSequences);

        TokenStringBuilder.formatErroSintaticoToString(e, errosSintaticos, tokensEsperados);

        if (tokensEsperados.contains("BEGIN")){
            errosSintaticos.append("Erro sint\u00e1tico: Programa deve iniciar com 'BEGIN'").append("\n\n");
        }else if (tokensEsperados.contains("START")){
            errosSintaticos.append("Erro sint\u00e1tico: Se\u00e7\u00e3o de comandos deve iniciar com 'START'").append("\n\n");
        }else if (tokensEsperados.contains("END") || tokensEsperados.contains("DOT")) {
            errosSintaticos.append("Erro sint\u00e1tico: Programa deve acabar com 'END.'").append("\n\n");
        }
        // RECUPERAÇÃO DE ERROS
        skipToSynchronizingToken(SEMICOLON, END, START, DEFINE);
    }
  }

  final public void NomeDoPrograma() throws ParseException {
    try {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case IDENTIFIER:
        jj_consume_token(IDENTIFIER);
        break;
      default:
        jj_la1[0] = jj_gen;
        ;
      }
    } catch (ParseException e) {
        errosSintaticosCount++;
        String tokensEsperados = getListaTokensEsperados(e.expectedTokenSequences);

        TokenStringBuilder.formatErroSintaticoToString(e, errosSintaticos, tokensEsperados);

        if (tokensEsperados.contains("IDENTIFIER")){
                errosSintaticos.append("Erro sint\u00e1tico: Nome do Programa deve ser um 'IDENTIFICADOR'").append("\n\n");
        }
        skipToSynchronizingToken(SEMICOLON, END, BEGIN);
    }
  }

  final public void Expressao() throws ParseException {
    try {
      ExpressaoAritmeticaOuLogica();
      ExpressaoAux();
    } catch (ParseException e) {
        errosSintaticosCount++;
        String tokensEsperados = getListaTokensEsperados(e.expectedTokenSequences);

        TokenStringBuilder.formatErroSintaticoToString(e, errosSintaticos, tokensEsperados);
        skipToSynchronizingToken(SEMICOLON, END, BEGIN, START, RPAREN, RBRACKET);
    }
  }

  final public void ExpressaoAux() throws ParseException {
    try {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case EQUAL:
      case NOT_EQUAL:
      case SHIFT_LEFT:
      case SHIFT_RIGHT:
      case SHIFT_LEFT_ASSIGN:
      case SHIFT_RIGHT_ASSIGN:
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case EQUAL:
          jj_consume_token(EQUAL);
          ExpressaoAritmeticaOuLogica();
          break;
        case NOT_EQUAL:
          jj_consume_token(NOT_EQUAL);
          ExpressaoAritmeticaOuLogica();
          break;
        case SHIFT_LEFT:
          jj_consume_token(SHIFT_LEFT);
          ExpressaoAritmeticaOuLogica();
          break;
        case SHIFT_RIGHT:
          jj_consume_token(SHIFT_RIGHT);
          ExpressaoAritmeticaOuLogica();
          break;
        case SHIFT_LEFT_ASSIGN:
          jj_consume_token(SHIFT_LEFT_ASSIGN);
          ExpressaoAritmeticaOuLogica();
          break;
        case SHIFT_RIGHT_ASSIGN:
          jj_consume_token(SHIFT_RIGHT_ASSIGN);
          ExpressaoAritmeticaOuLogica();
          break;
        default:
          jj_la1[1] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
        break;
      default:
        jj_la1[2] = jj_gen;
        ;
      }
    } catch (ParseException e) {
        errosSintaticosCount++;
        String tokensEsperados = getListaTokensEsperados(e.expectedTokenSequences);

        TokenStringBuilder.formatErroSintaticoToString(e, errosSintaticos, tokensEsperados);

        if(tokensEsperados.contains("EQUAL") || tokensEsperados.contains("NOT_EQUAL") || tokensEsperados.contains("SHIFT_LEFT")
            || tokensEsperados.contains("SHIFT_RIGHT") || tokensEsperados.contains("SHIFT_LEFT_ASSIGN") || tokensEsperados.contains("SHIFT_RIGHT_ASSIGN"))
        {
            errosSintaticos.append("Erro sint\u00e1tico: A Express\u00e3o deve conter um operador l\u00f3gico").append("\n\n");
        }
        skipToSynchronizingToken(SEMICOLON, END, RPAREN, RBRACKET, START);
    }
  }

  final public void ExpressaoAritmeticaOuLogica() throws ParseException {
    try {
      Termo2();
      MenorPrioridade();
    } catch (ParseException e) {
        errosSintaticosCount++;
        String tokensEsperados = getListaTokensEsperados(e.expectedTokenSequences);

        TokenStringBuilder.formatErroSintaticoToString(e, errosSintaticos, tokensEsperados);
        skipToSynchronizingToken(SEMICOLON, END, RPAREN, RBRACKET, START);
    }
  }

  final public void MenorPrioridade() throws ParseException {
    try {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case PLUS:
      case MINUS:
      case PIPE:
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case PLUS:
          jj_consume_token(PLUS);
          Termo2();
          MenorPrioridade();
          break;
        case MINUS:
          jj_consume_token(MINUS);
          Termo2();
          MenorPrioridade();
          break;
        case PIPE:
          jj_consume_token(PIPE);
          Termo2();
          MenorPrioridade();
          break;
        default:
          jj_la1[3] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
        break;
      default:
        jj_la1[4] = jj_gen;
        ;
      }
    } catch (ParseException e) {
        errosSintaticosCount++;
        String tokensEsperados = getListaTokensEsperados(e.expectedTokenSequences);

        TokenStringBuilder.formatErroSintaticoToString(e, errosSintaticos, tokensEsperados);

        if(tokensEsperados.contains("PLUS") || tokensEsperados.contains("MINUS") || tokensEsperados.contains("PIPE")){
            errosSintaticos.append("Erro sint\u00e1tico: A Express\u00e3o deve conter um operador aritm\u00e9tico").append("\n\n");
        }
        skipToSynchronizingToken(SEMICOLON, END, START, RPAREN, RBRACKET);
    }
  }

  final public void Termo2() throws ParseException {
    try {
      Termo1();
      MediaPrioridade();
    } catch (ParseException e) {
        errosSintaticosCount++;
        String tokensEsperados = getListaTokensEsperados(e.expectedTokenSequences);

        TokenStringBuilder.formatErroSintaticoToString(e, errosSintaticos, tokensEsperados);
        skipToSynchronizingToken(SEMICOLON, END, START, RPAREN, RBRACKET);
    }
  }

  final public void MediaPrioridade() throws ParseException {
    try {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case STAR:
      case SLASH:
      case PERCENT:
      case DOUBLE_PERCENT:
      case AMPERSAND:
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case STAR:
          jj_consume_token(STAR);
          Termo1();
          MediaPrioridade();
          break;
        case SLASH:
          jj_consume_token(SLASH);
          Termo1();
          MediaPrioridade();
          break;
        case PERCENT:
          jj_consume_token(PERCENT);
          Termo1();
          MediaPrioridade();
          break;
        case DOUBLE_PERCENT:
          jj_consume_token(DOUBLE_PERCENT);
          Termo1();
          MediaPrioridade();
          break;
        case AMPERSAND:
          jj_consume_token(AMPERSAND);
          Termo1();
          MediaPrioridade();
          break;
        default:
          jj_la1[5] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
        break;
      default:
        jj_la1[6] = jj_gen;
        ;
      }
    } catch (ParseException e) {
        errosSintaticosCount++;
        String tokensEsperados = getListaTokensEsperados(e.expectedTokenSequences);

        TokenStringBuilder.formatErroSintaticoToString(e, errosSintaticos, tokensEsperados);

        if(tokensEsperados.contains("STAR") || tokensEsperados.contains("SLASH") || tokensEsperados.contains("PERCENT")
            || tokensEsperados.contains("DOUBLE_PERCENT") || tokensEsperados.contains("AMPERSAND"))
        {
            errosSintaticos.append("Erro sint\u00e1tico: A Express\u00e3o deve conter um operador aritm\u00e9tico").append("\n\n");
        }
        skipToSynchronizingToken(SEMICOLON, END, START, RPAREN, RBRACKET);
    }
  }

  final public void Termo1() throws ParseException {
    try {
      Elemento();
      MaiorPrioridade();
    } catch (ParseException e) {
        errosSintaticosCount++;
        String tokensEsperados = getListaTokensEsperados(e.expectedTokenSequences);

        TokenStringBuilder.formatErroSintaticoToString(e, errosSintaticos, tokensEsperados);
        skipToSynchronizingToken(SEMICOLON, END, START, RPAREN, RBRACKET);
    }
  }

  final public void MaiorPrioridade() throws ParseException {
    try {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case POWER:
        jj_consume_token(POWER);
        Elemento();
        MaiorPrioridade();
        break;
      default:
        jj_la1[7] = jj_gen;
        ;
      }
    } catch (ParseException e) {
        errosSintaticosCount++;
        String tokensEsperados = getListaTokensEsperados(e.expectedTokenSequences);

        TokenStringBuilder.formatErroSintaticoToString(e, errosSintaticos, tokensEsperados);

        if(tokensEsperados.contains("POWER")){
             errosSintaticos.append("Erro sint\u00e1tico: A Express\u00e3o deve conter o operador '**'").append("\n\n");
        }
        skipToSynchronizingToken(SEMICOLON, END, START, RPAREN, RBRACKET);
    }
  }

  final public void Elemento() throws ParseException {
    try {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case IDENTIFIER:
        jj_consume_token(IDENTIFIER);
        SufixoIdentificador();
        break;
      case NUMBER:
        jj_consume_token(NUMBER);
        break;
      case REAL:
        jj_consume_token(REAL);
        break;
      case TEXT_DOUBLE:
        jj_consume_token(TEXT_DOUBLE);
        break;
      case TEXT_SINGLE:
        jj_consume_token(TEXT_SINGLE);
        break;
      case TRUE:
        jj_consume_token(TRUE);
        break;
      case FALSE:
        jj_consume_token(FALSE);
        break;
      case LPAREN:
        jj_consume_token(LPAREN);
        Expressao();
        jj_consume_token(RPAREN);
        break;
      case EXCLAMATION:
        jj_consume_token(EXCLAMATION);
        jj_consume_token(LPAREN);
        Expressao();
        jj_consume_token(RPAREN);
        break;
      default:
        jj_la1[8] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    } catch (ParseException e) {
        errosSintaticosCount++;
        String tokensEsperados = getListaTokensEsperados(e.expectedTokenSequences);

        TokenStringBuilder.formatErroSintaticoToString(e, errosSintaticos, tokensEsperados);

        if (tokensEsperados.contains("IDENTIFIER") || tokensEsperados.contains("NUMBER") || tokensEsperados.contains("REAL") || tokensEsperados.contains("TEXT_DOUBLE")
            || tokensEsperados.contains("TEXT_SINGLE") || tokensEsperados.contains("TRUE") || tokensEsperados.contains("FALSE"))
        {
            errosSintaticos.append("Erro sint\u00e1tico: Elemento deve pertencer ao conjunto: {'Identificador', 'Constante num\u00e9rica', 'Constante num\u00e9rica real', 'Constante literal', 'TRUE' ou 'FALSE'}").append("\n\n");
        }else if (tokensEsperados.contains("LPAREN") || tokensEsperados.contains("RPAREN")){
            errosSintaticos.append("Erro sint\u00e1tico: Elemento deve estar entre '(' e ')'").append("\n\n");
        }else if (tokensEsperados.contains("EXCLAMATION")){
            errosSintaticos.append("Erro sint\u00e1tico: Elemento deve estar entre '!(' e ')'").append("\n\n");
        }
        skipToSynchronizingToken(SEMICOLON, END, START, RPAREN, RBRACKET, LPAREN, LBRACKET);
    }
  }

  final public void ListaDeElementos() throws ParseException {
    try {
      Elemento();
      ListaDeElementosAux();
    } catch (ParseException e) {
        errosSintaticosCount++;
        String tokensEsperados = getListaTokensEsperados(e.expectedTokenSequences);

        TokenStringBuilder.formatErroSintaticoToString(e, errosSintaticos, tokensEsperados);
        skipToSynchronizingToken(SEMICOLON, END, START, RPAREN, RBRACKET, COMMA);
    }
  }

  final public void ListaDeElementosAux() throws ParseException {
    try {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case COMMA:
        jj_consume_token(COMMA);
        Elemento();
        ListaDeElementosAux();
        break;
      default:
        jj_la1[9] = jj_gen;
        ;
      }
    } catch (ParseException e) {
        errosSintaticosCount++;
        String tokensEsperados = getListaTokensEsperados(e.expectedTokenSequences);

        TokenStringBuilder.formatErroSintaticoToString(e, errosSintaticos, tokensEsperados);

        if(tokensEsperados.contains("COMMA")){
             errosSintaticos.append("Erro sint\u00e1tico: Elementos devem estar separados por ','").append("\n\n");
        }
        skipToSynchronizingToken(SEMICOLON, END, START, RPAREN, RBRACKET, COMMA);
    }
  }

  final public void ListaIdentificadores() throws ParseException {
    try {
      jj_consume_token(IDENTIFIER);
      ListaIdentificadoresAux();
    } catch (ParseException e) {
        errosSintaticosCount++;
        String tokensEsperados = getListaTokensEsperados(e.expectedTokenSequences);

        TokenStringBuilder.formatErroSintaticoToString(e, errosSintaticos, tokensEsperados);

        if(tokensEsperados.contains("IDENTIFIER")){
             errosSintaticos.append("Erro sint\u00e1tico: Deve conter ao menos um 'Identificador'").append("\n\n");
        }
        skipToSynchronizingToken(SEMICOLON, END, START, COMMA);
    }
  }

  final public void ListaIdentificadoresAux() throws ParseException {
    try {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case COMMA:
        jj_consume_token(COMMA);
        jj_consume_token(IDENTIFIER);
        ListaIdentificadoresAux();
        break;
      default:
        jj_la1[10] = jj_gen;
        ;
      }
    } catch (ParseException e) {
        errosSintaticosCount++;
        String tokensEsperados = getListaTokensEsperados(e.expectedTokenSequences);

        TokenStringBuilder.formatErroSintaticoToString(e, errosSintaticos, tokensEsperados);

        if(tokensEsperados.contains("COMMA")){
             errosSintaticos.append("Erro sint\u00e1tico: Elementos devem estar separados por ','").append("\n\n");
        }else if(tokensEsperados.contains("IDENTIFIER")){
            errosSintaticos.append("Erro sint\u00e1tico: Deve conter ao menos um 'Identificador' ap\u00f3s a ','").append("\n\n");
        }
        skipToSynchronizingToken(SEMICOLON, END, START, COMMA);
    }
  }

  final public void Variavel() throws ParseException {
    try {
      ListaIdentificadores();
      jj_consume_token(COLON);
      DeclaracaoTipo();
      jj_consume_token(SEMICOLON);
    } catch (ParseException e) {
        errosSintaticosCount++;
        String tokensEsperados = getListaTokensEsperados(e.expectedTokenSequences);

        TokenStringBuilder.formatErroSintaticoToString(e, errosSintaticos, tokensEsperados);

        if(tokensEsperados.contains("COLON")){
             errosSintaticos.append("Erro sint\u00e1tico: Declara\u00e7\u00e3o de vari\u00e1vel deve conter ':' ap\u00f3s a lista de vari\u00e1veis").append("\n\n");
        }else if(tokensEsperados.contains("SEMICOLON")){
            errosSintaticos.append("Erro sint\u00e1tico: Declara\u00e7\u00e3o da vari\u00e1vel deve terminar com ';' ap\u00f3s especifica\u00e7\u00e3o do tipo").append("\n\n");
        }
        skipToSynchronizingToken(SEMICOLON, END, START);
    }
  }

  final public void Tipo() throws ParseException {
    try {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case TYPE_NUM:
        jj_consume_token(TYPE_NUM);
        break;
      case TYPE_REAL:
        jj_consume_token(TYPE_REAL);
        break;
      case TYPE_TEXT:
        jj_consume_token(TYPE_TEXT);
        break;
      case TYPE_FLAG:
        jj_consume_token(TYPE_FLAG);
        break;
      default:
        jj_la1[11] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    } catch (ParseException e) {
        errosSintaticosCount++;
        String tokensEsperados = getListaTokensEsperados(e.expectedTokenSequences);

        TokenStringBuilder.formatErroSintaticoToString(e, errosSintaticos, tokensEsperados);

        if(tokensEsperados.contains("TYPE_NUM") || tokensEsperados.contains("TYPE_REAL") || tokensEsperados.contains("TYPE_TEXT") || tokensEsperados.contains("TYPE_FLAG")){
             errosSintaticos.append("Erro sint\u00e1tico: Tipo declarado deve pertencer ao conjunto: {'NUM', 'REAL' 'TEXT' 'FLAG'}").append("\n\n");
        }
        skipToSynchronizingToken(SEMICOLON, END, START, COLON);
    }
  }

  final public void DeclaracaoTipo() throws ParseException {
    try {
      Tipo();
      SufixoDoTipo();
    } catch (ParseException e) {
        errosSintaticosCount++;
        String tokensEsperados = getListaTokensEsperados(e.expectedTokenSequences);
        TokenStringBuilder.formatErroSintaticoToString(e, errosSintaticos, tokensEsperados);
        skipToSynchronizingToken(SEMICOLON, END, START, ASSIGN);
    }
  }

  final public void SufixoDoTipo() throws ParseException {
    try {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case ASSIGN:
      case LBRACKET:
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case ASSIGN:
          jj_consume_token(ASSIGN);
          Elemento();
          break;
        case LBRACKET:
          DeclaracaoArray();
          break;
        default:
          jj_la1[12] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
        break;
      default:
        jj_la1[13] = jj_gen;
        ;
      }
    } catch (ParseException e) {
        errosSintaticosCount++;
        String tokensEsperados = getListaTokensEsperados(e.expectedTokenSequences);

        TokenStringBuilder.formatErroSintaticoToString(e, errosSintaticos, tokensEsperados);

        if(tokensEsperados.contains("=")){
            errosSintaticos.append("Erro sint\u00e1tico: Atribui\u00e7\u00f5es devem ser feitas a partir do simbolo '='").append("\n\n");
        }
        skipToSynchronizingToken(SEMICOLON, END, START);
    }
  }

  final public void DeclaracaoArray() throws ParseException {
    try {
      jj_consume_token(LBRACKET);
      jj_consume_token(NUMBER);
      jj_consume_token(RBRACKET);
      DeclaracaoValoresArray();
    } catch (ParseException e) {
        errosSintaticosCount++;
        String tokensEsperados = getListaTokensEsperados(e.expectedTokenSequences);

        TokenStringBuilder.formatErroSintaticoToString(e, errosSintaticos, tokensEsperados);

        if(tokensEsperados.contains("[") || tokensEsperados.contains("]")){
            errosSintaticos.append("Erro sint\u00e1tico: Declara\u00e7\u00e3o de tamanho do array deve ser feita entre '[' e ']'").append("\n\n");
        }
        skipToSynchronizingToken(SEMICOLON, END, START, RBRACKET);
    }
  }

  final public void DeclaracaoValoresArray() throws ParseException {
    try {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case ASSIGN:
        jj_consume_token(ASSIGN);
        jj_consume_token(LBRACE);
        ListaDeElementos();
        jj_consume_token(RBRACE);
        break;
      default:
        jj_la1[14] = jj_gen;
        ;
      }
    } catch (ParseException e) {
        errosSintaticosCount++;
        String tokensEsperados = getListaTokensEsperados(e.expectedTokenSequences);

        TokenStringBuilder.formatErroSintaticoToString(e, errosSintaticos, tokensEsperados);

        if(tokensEsperados.contains("=")){
            errosSintaticos.append("Erro sint\u00e1tico: Atribui\u00e7\u00f5es devem ser feitas a partir do simbolo '='").append("\n\n");
        }
        if(tokensEsperados.contains("{") || tokensEsperados.contains("}")){
            errosSintaticos.append("Erro sint\u00e1tico: Declara\u00e7\u00f5es de valores dentro de arrays devem ser feitas entre '{' e '}'").append("\n\n");
        }
        skipToSynchronizingToken(SEMICOLON, END, START, RBRACE);
    }
  }

  final public void ListaDeVariaveis() throws ParseException {
    try {
      Variavel();
      ListaDeVariaveisAux();
    } catch (ParseException e) {
        errosSintaticosCount++;
        String tokensEsperados = getListaTokensEsperados(e.expectedTokenSequences);

        TokenStringBuilder.formatErroSintaticoToString(e, errosSintaticos, tokensEsperados);

        if(tokensEsperados.contains(";")){
            errosSintaticos.append("Erro sint\u00e1tico: Declara\u00e7\u00f5es de vari\u00e1veis devem ser separadas por ';'").append("\n\n");
        }
        skipToSynchronizingToken(SEMICOLON, END, START);
    }
  }

  final public void ListaDeVariaveisAux() throws ParseException {
    try {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case IDENTIFIER:
        Variavel();
        ListaDeVariaveisAux();
        break;
      default:
        jj_la1[15] = jj_gen;
        ;
      }
    } catch (ParseException e) {
        errosSintaticosCount++;
        String tokensEsperados = getListaTokensEsperados(e.expectedTokenSequences);

        TokenStringBuilder.formatErroSintaticoToString(e, errosSintaticos, tokensEsperados);
        skipToSynchronizingToken(SEMICOLON, END, START);
    }
  }

  final public void BlocoDefine() throws ParseException {
    try {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case DEFINE:
        jj_consume_token(DEFINE);
        ListaDeVariaveis();
        break;
      default:
        jj_la1[16] = jj_gen;
        ;
      }
    } catch (ParseException e) {
        errosSintaticosCount++;
        String tokensEsperados = getListaTokensEsperados(e.expectedTokenSequences);

        TokenStringBuilder.formatErroSintaticoToString(e, errosSintaticos, tokensEsperados);
        skipToSynchronizingToken(SEMICOLON, END, START);
    }
  }

  final public void Atribuicao() throws ParseException {
    try {
      jj_consume_token(SET);
      jj_consume_token(IDENTIFIER);
      SufixoDaAtribuicao();
    } catch (ParseException e) {
        errosSintaticosCount++;
        String tokensEsperados = getListaTokensEsperados(e.expectedTokenSequences);

        TokenStringBuilder.formatErroSintaticoToString(e, errosSintaticos, tokensEsperados);
        skipToSynchronizingToken(SEMICOLON, END, READ, SHOW, IF, LOOP);
    }
  }

  final public void SufixoDaAtribuicao() throws ParseException {
    try {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case ASSIGN:
        jj_consume_token(ASSIGN);
        Expressao();
        break;
      case LBRACKET:
        jj_consume_token(LBRACKET);
        Expressao();
        jj_consume_token(RBRACKET);
        jj_consume_token(ASSIGN);
        Expressao();
        break;
      default:
        jj_la1[17] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    } catch (ParseException e) {
        errosSintaticosCount++;
        String tokensEsperados = getListaTokensEsperados(e.expectedTokenSequences);

        TokenStringBuilder.formatErroSintaticoToString(e, errosSintaticos, tokensEsperados);

         if(tokensEsperados.contains("=")){
            errosSintaticos.append("Erro sint\u00e1tico: Atribui\u00e7\u00f5es devem ser feitas a partir do simbolo '='").append("\n\n");
         }
         if(tokensEsperados.contains("[") || tokensEsperados.contains("]")){
            errosSintaticos.append("Erro sint\u00e1tico: Para atribuir um valor a uma posi\u00e7\u00e3o de um array, deve se seguir o formato <variavel>[<indice>] = <valor atribuido>").append("\n\n");
         }
         skipToSynchronizingToken(SEMICOLON, END, READ, SHOW, IF, LOOP, RBRACKET);
    }
  }

  final public void EntradaDeDados() throws ParseException {
    try {
      jj_consume_token(READ);
      jj_consume_token(LPAREN);
      jj_consume_token(IDENTIFIER);
      SufixoIdentificador();
      jj_consume_token(RPAREN);
    } catch (ParseException e) {
        errosSintaticosCount++;
        String tokensEsperados = getListaTokensEsperados(e.expectedTokenSequences);

        TokenStringBuilder.formatErroSintaticoToString(e, errosSintaticos, tokensEsperados);

        if(tokensEsperados.contains("(") || tokensEsperados.contains(")")){
            errosSintaticos.append("Erro sint\u00e1tico: A variavel destino da entrada de dados deve ser especificada entre '(' e')')").append("\n\n");
        }
        skipToSynchronizingToken(SEMICOLON, END, READ, SHOW, IF, LOOP, RPAREN);
    }
  }

  final public void SufixoIdentificador() throws ParseException {
    try {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case LBRACKET:
        jj_consume_token(LBRACKET);
        Expressao();
        jj_consume_token(RBRACKET);
        break;
      default:
        jj_la1[18] = jj_gen;
        ;
      }
    } catch (ParseException e) {
        errosSintaticosCount++;
        String tokensEsperados = getListaTokensEsperados(e.expectedTokenSequences);

        TokenStringBuilder.formatErroSintaticoToString(e, errosSintaticos, tokensEsperados);

        if(tokensEsperados.contains("[") || tokensEsperados.contains("]")){
            errosSintaticos.append("Erro sint\u00e1tico: Indices de vetores devem ser explicitos entre '[' e ']' ").append("\n\n");
        }
        skipToSynchronizingToken(SEMICOLON, END, READ, SHOW, IF, LOOP, RBRACKET);
    }
  }

  final public void SaidaDeDados() throws ParseException {
    try {
      jj_consume_token(SHOW);
      jj_consume_token(LPAREN);
      ListaDeElementos();
      jj_consume_token(RPAREN);
    } catch (ParseException e) {
        errosSintaticosCount++;
        String tokensEsperados = getListaTokensEsperados(e.expectedTokenSequences);

        TokenStringBuilder.formatErroSintaticoToString(e, errosSintaticos, tokensEsperados);

        if(tokensEsperados.contains("(") || tokensEsperados.contains(")")){
            errosSintaticos.append("Erro Sintatico: O conteudo a ser mostrado deve estar entre '(' e ')'").append("\n\n");
        }
        skipToSynchronizingToken(SEMICOLON, END, READ, SHOW, IF, LOOP, RPAREN);
    }
  }

  final public void Selecao() throws ParseException {
    try {
      jj_consume_token(IF);
      Expressao();
      jj_consume_token(THEN);
      ListaDeComandos();
      Else();
      jj_consume_token(END);
    } catch (ParseException e) {
        errosSintaticosCount++;
        String tokensEsperados = getListaTokensEsperados(e.expectedTokenSequences);

        TokenStringBuilder.formatErroSintaticoToString(e, errosSintaticos, tokensEsperados);

        if(tokensEsperados.contains("IF") || tokensEsperados.contains("THEN") || tokensEsperados.contains("END")){
            errosSintaticos.append("Erro sint\u00e1tico: Comandos de sele\u00e7\u00e3o devem ter seguir o formato 'IF <condi\u00e7\u00e3o> THEN <comandos> END'").append("\n\n");
        }
        skipToSynchronizingToken(SEMICOLON, END, READ, SHOW, IF, LOOP, THEN);
    }
  }

  final public void Else() throws ParseException {
    try {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case ELSE:
        jj_consume_token(ELSE);
        ListaDeComandos();
        break;
      default:
        jj_la1[19] = jj_gen;
        ;
      }
    } catch (ParseException e) {
        errosSintaticosCount++;
        String tokensEsperados = getListaTokensEsperados(e.expectedTokenSequences);

        TokenStringBuilder.formatErroSintaticoToString(e, errosSintaticos, tokensEsperados);

        if(tokensEsperados.contains("ELSE")){
            errosSintaticos.append("Erro sint\u00e1tico: O comando 'Se n\u00e3o' se inicia atrav\u00e9s de comando 'ELSE'").append("\n\n");
        }
        skipToSynchronizingToken(SEMICOLON, END, READ, SHOW, IF, LOOP, THEN);
    }
  }

  final public void Repeticao() throws ParseException {
    try {
      jj_consume_token(LOOP);
      jj_consume_token(WHILE);
      Expressao();
      ListaDeComandos();
      jj_consume_token(END);
    } catch (ParseException e) {
        errosSintaticosCount++;
        String tokensEsperados = getListaTokensEsperados(e.expectedTokenSequences);

        TokenStringBuilder.formatErroSintaticoToString(e, errosSintaticos, tokensEsperados);

        if(tokensEsperados.contains("LOOP") || tokensEsperados.contains("WHILE") || tokensEsperados.contains("END")){
            errosSintaticos.append("Erro sint\u00e1tico: Comandos de repeti\u00e7\u00e3o devem seguir o formato 'LOOP WHILE <comandos> END").append("\n\n");
        }
        skipToSynchronizingToken(SEMICOLON, END, READ, SHOW, IF, LOOP);
    }
  }

  final public void Comando() throws ParseException {
    try {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case SET:
        Atribuicao();
        break;
      case READ:
        EntradaDeDados();
        break;
      case SHOW:
        SaidaDeDados();
        break;
      case IF:
        Selecao();
        break;
      case LOOP:
        Repeticao();
        break;
      default:
        jj_la1[20] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    } catch (ParseException e) {
        errosSintaticosCount++;
        String tokensEsperados = getListaTokensEsperados(e.expectedTokenSequences);

        TokenStringBuilder.formatErroSintaticoToString(e, errosSintaticos, tokensEsperados);

        if(tokensEsperados.contains("SET") || tokensEsperados.contains("READ") || tokensEsperados.contains("SHOW") || tokensEsperados.contains("IF") ||  tokensEsperados.contains("LOOP")){
            errosSintaticos.append("Erro sint\u00e1tico: Comando n\u00e3o especificado ou especificado errado, os comandos s\u00e3o: SET, READ, SHOW, IF, LOOP").append("\n\n");
        }
        skipToSynchronizingToken(SEMICOLON, END, READ, SHOW, IF, LOOP);
    }
  }

  final public void ListaDeComandos() throws ParseException {
    try {
      Comando();
      jj_consume_token(SEMICOLON);
      ListaDeComandosAux();
    } catch (ParseException e) {
        errosSintaticosCount++;
        String tokensEsperados = getListaTokensEsperados(e.expectedTokenSequences);

        TokenStringBuilder.formatErroSintaticoToString(e, errosSintaticos, tokensEsperados);
        if (tokensEsperados.contains(";")){
            errosSintaticos.append("Erro sint\u00e1tico: Todo comando deve ser finalizado com ';'").append("\n\n");
        }
        skipToSynchronizingToken(SEMICOLON, END, READ, SHOW, IF, LOOP);
    }
  }

  final public void ListaDeComandosAux() throws ParseException {
    try {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case SET:
      case READ:
      case SHOW:
      case IF:
      case LOOP:
        Comando();
        jj_consume_token(SEMICOLON);
        ListaDeComandosAux();
        break;
      default:
        jj_la1[21] = jj_gen;
        ;
      }
    } catch (ParseException e) {
        errosSintaticosCount++;
        String tokensEsperados = getListaTokensEsperados(e.expectedTokenSequences);

        TokenStringBuilder.formatErroSintaticoToString(e, errosSintaticos, tokensEsperados);
        skipToSynchronizingToken(SEMICOLON, END, READ, SHOW, IF, LOOP);
    }
  }

  /** Generated Token Manager. */
  public Linguagem20252TokenManager token_source;
  SimpleCharStream jj_input_stream;
  /** Current token. */
  public Token token;
  /** Next token. */
  public Token jj_nt;
  private int jj_ntk;
  private int jj_gen;
  final private int[] jj_la1 = new int[22];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static {
      jj_la1_init_0();
      jj_la1_init_1();
   }
   private static void jj_la1_init_0() {
      jj_la1_0 = new int[] {0x0,0x60000,0x60000,0x60000000,0x60000000,0x80000000,0x80000000,0x0,0x8001d00,0x200000,0x200000,0x0,0x2010000,0x2010000,0x10000,0x0,0x0,0x2010000,0x2000000,0x0,0x0,0x0,};
   }
   private static void jj_la1_init_1() {
      jj_la1_1 = new int[] {0x40000000,0xf0,0xf0,0x200,0x200,0x40b,0x40b,0x4,0x58000100,0x0,0x0,0x7800,0x0,0x0,0x0,0x40000000,0x10000,0x0,0x0,0x1000000,0x2780000,0x2780000,};
   }

  /** Constructor with InputStream. */
  public Linguagem20252(java.io.InputStream stream) {
     this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public Linguagem20252(java.io.InputStream stream, String encoding) {
    try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source = new Linguagem20252TokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 22; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream) {
     ReInit(stream, null);
  }
  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream, String encoding) {
    try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 22; i++) jj_la1[i] = -1;
  }

  /** Constructor. */
  public Linguagem20252(java.io.Reader stream) {
    jj_input_stream = new SimpleCharStream(stream, 1, 1);
    token_source = new Linguagem20252TokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 22; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(java.io.Reader stream) {
    jj_input_stream.ReInit(stream, 1, 1);
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 22; i++) jj_la1[i] = -1;
  }

  /** Constructor with generated Token Manager. */
  public Linguagem20252(Linguagem20252TokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 22; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(Linguagem20252TokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 22; i++) jj_la1[i] = -1;
  }

  private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }


/** Get the next Token. */
  final public Token getNextToken() {
    if (token.next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    jj_gen++;
    return token;
  }

/** Get the specific Token. */
  final public Token getToken(int index) {
    Token t = token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) t = t.next;
      else t = t.next = token_source.getNextToken();
    }
    return t;
  }

  private int jj_ntk() {
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  private java.util.List jj_expentries = new java.util.ArrayList();
  private int[] jj_expentry;
  private int jj_kind = -1;

  /** Generate ParseException. */
  public ParseException generateParseException() {
    jj_expentries.clear();
    boolean[] la1tokens = new boolean[64];
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 22; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
          if ((jj_la1_1[i] & (1<<j)) != 0) {
            la1tokens[32+j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 64; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.add(jj_expentry);
      }
    }
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = (int[])jj_expentries.get(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  /** Enable tracing. */
  final public void enable_tracing() {
  }

  /** Disable tracing. */
  final public void disable_tracing() {
  }

}
