/* Generated By:JavaCC: Do not edit this line. Linguagem20252Constants.java */
package app;


/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface Linguagem20252Constants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int BLANK_SPACE = 1;
  /** RegularExpression Id. */
  int END_OF_LINE = 2;
  /** RegularExpression Id. */
  int NEW_LINE = 3;
  /** RegularExpression Id. */
  int TABULATION = 4;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 5;
  /** RegularExpression Id. */
  int BLOCK_COMMENT = 6;
  /** RegularExpression Id. */
  int MALFORMED_REAL = 7;
  /** RegularExpression Id. */
  int REAL = 8;
  /** RegularExpression Id. */
  int MALFORMED_NUMBER = 9;
  /** RegularExpression Id. */
  int NUMBER = 10;
  /** RegularExpression Id. */
  int TEXT_DOUBLE = 11;
  /** RegularExpression Id. */
  int TEXT_SINGLE = 12;
  /** RegularExpression Id. */
  int UNCLOSED_STRING = 13;
  /** RegularExpression Id. */
  int UNCLOSED_QUOTE = 14;
  /** RegularExpression Id. */
  int UNCLOSED_BLOCK_COMMENT = 15;
  /** RegularExpression Id. */
  int ASSIGN = 16;
  /** RegularExpression Id. */
  int EQUAL = 17;
  /** RegularExpression Id. */
  int NOT_EQUAL = 18;
  /** RegularExpression Id. */
  int SEMICOLON = 19;
  /** RegularExpression Id. */
  int COLON = 20;
  /** RegularExpression Id. */
  int COMMA = 21;
  /** RegularExpression Id. */
  int DOT = 22;
  /** RegularExpression Id. */
  int LBRACE = 23;
  /** RegularExpression Id. */
  int RBRACE = 24;
  /** RegularExpression Id. */
  int LBRACKET = 25;
  /** RegularExpression Id. */
  int RBRACKET = 26;
  /** RegularExpression Id. */
  int LPAREN = 27;
  /** RegularExpression Id. */
  int RPAREN = 28;
  /** RegularExpression Id. */
  int PLUS = 29;
  /** RegularExpression Id. */
  int MINUS = 30;
  /** RegularExpression Id. */
  int STAR = 31;
  /** RegularExpression Id. */
  int SLASH = 32;
  /** RegularExpression Id. */
  int PERCENT = 33;
  /** RegularExpression Id. */
  int POWER = 34;
  /** RegularExpression Id. */
  int DOUBLE_PERCENT = 35;
  /** RegularExpression Id. */
  int SHIFT_LEFT = 36;
  /** RegularExpression Id. */
  int SHIFT_RIGHT = 37;
  /** RegularExpression Id. */
  int SHIFT_LEFT_ASSIGN = 38;
  /** RegularExpression Id. */
  int SHIFT_RIGHT_ASSIGN = 39;
  /** RegularExpression Id. */
  int EXCLAMATION = 40;
  /** RegularExpression Id. */
  int PIPE = 41;
  /** RegularExpression Id. */
  int AMPERSAND = 42;
  /** RegularExpression Id. */
  int TYPE_NUM = 43;
  /** RegularExpression Id. */
  int TYPE_REAL = 44;
  /** RegularExpression Id. */
  int TYPE_TEXT = 45;
  /** RegularExpression Id. */
  int TYPE_FLAG = 46;
  /** RegularExpression Id. */
  int BEGIN = 47;
  /** RegularExpression Id. */
  int DEFINE = 48;
  /** RegularExpression Id. */
  int START = 49;
  /** RegularExpression Id. */
  int END = 50;
  /** RegularExpression Id. */
  int SET = 51;
  /** RegularExpression Id. */
  int READ = 52;
  /** RegularExpression Id. */
  int SHOW = 53;
  /** RegularExpression Id. */
  int IF = 54;
  /** RegularExpression Id. */
  int THEN = 55;
  /** RegularExpression Id. */
  int ELSE = 56;
  /** RegularExpression Id. */
  int LOOP = 57;
  /** RegularExpression Id. */
  int WHILE = 58;
  /** RegularExpression Id. */
  int TRUE = 59;
  /** RegularExpression Id. */
  int FALSE = 60;
  /** RegularExpression Id. */
  int MALFORMED_IDENTIFIER = 61;
  /** RegularExpression Id. */
  int IDENTIFIER = 62;
  /** RegularExpression Id. */
  int INVALID_SIMBOL = 63;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\t\"",
    "<SINGLE_LINE_COMMENT>",
    "<BLOCK_COMMENT>",
    "<MALFORMED_REAL>",
    "<REAL>",
    "<MALFORMED_NUMBER>",
    "<NUMBER>",
    "<TEXT_DOUBLE>",
    "<TEXT_SINGLE>",
    "<UNCLOSED_STRING>",
    "<UNCLOSED_QUOTE>",
    "<UNCLOSED_BLOCK_COMMENT>",
    "\"=\"",
    "\"==\"",
    "\"!=\"",
    "\";\"",
    "\":\"",
    "\",\"",
    "\".\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\"(\"",
    "\")\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"**\"",
    "\"%%\"",
    "\"<<\"",
    "\">>\"",
    "\"<<=\"",
    "\">>=\"",
    "\"!\"",
    "\"|\"",
    "\"&\"",
    "<TYPE_NUM>",
    "<TYPE_REAL>",
    "<TYPE_TEXT>",
    "<TYPE_FLAG>",
    "<BEGIN>",
    "<DEFINE>",
    "<START>",
    "<END>",
    "<SET>",
    "<READ>",
    "<SHOW>",
    "<IF>",
    "<THEN>",
    "<ELSE>",
    "<LOOP>",
    "<WHILE>",
    "<TRUE>",
    "<FALSE>",
    "<MALFORMED_IDENTIFIER>",
    "<IDENTIFIER>",
    "<INVALID_SIMBOL>",
  };

}
