/* Generated By:JavaCC: Do not edit this line. Linguagem20252.java */
package app;

import java.io.InputStream;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

public class Linguagem20252 implements Linguagem20252Constants {

    public static java.util.ArrayList analisar(InputStream input) throws ParseException {
            Linguagem20252 lexer = new Linguagem20252(input);
            java.util.ArrayList tokens = new java.util.ArrayList();
            Token token;
            do {
                token = lexer.getNextToken();
                tokens.add(token);
            } while (token.kind != Linguagem20252Constants.EOF);

            return tokens;
        }

  final public void Programa() throws ParseException {
    jj_consume_token(BEGIN);
    NomeDoPrograma();
    BlocoDefine();
    jj_consume_token(START);
    ListaDeComandos();
    jj_consume_token(END);
    jj_consume_token(DOT);
  }

  final public void NomeDoPrograma() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case IDENTIFIER:
      jj_consume_token(IDENTIFIER);
      break;
    default:
      jj_la1[0] = jj_gen;
      ;
    }
  }

  final public void Expressao() throws ParseException {
    ExpressaoAritmeticaOuLogica();
    ExpressaoAux();
  }

  final public void ExpressaoAux() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case EQUAL:
    case NOT_EQUAL:
    case SHIFT_LEFT:
    case SHIFT_RIGHT:
    case SHIFT_LEFT_ASSIGN:
    case SHIFT_RIGHT_ASSIGN:
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case EQUAL:
        jj_consume_token(EQUAL);
        ExpressaoAritmeticaOuLogica();
        break;
      case NOT_EQUAL:
        jj_consume_token(NOT_EQUAL);
        ExpressaoAritmeticaOuLogica();
        break;
      case SHIFT_LEFT:
        jj_consume_token(SHIFT_LEFT);
        ExpressaoAritmeticaOuLogica();
        break;
      case SHIFT_RIGHT:
        jj_consume_token(SHIFT_RIGHT);
        ExpressaoAritmeticaOuLogica();
        break;
      case SHIFT_LEFT_ASSIGN:
        jj_consume_token(SHIFT_LEFT_ASSIGN);
        ExpressaoAritmeticaOuLogica();
        break;
      case SHIFT_RIGHT_ASSIGN:
        jj_consume_token(SHIFT_RIGHT_ASSIGN);
        ExpressaoAritmeticaOuLogica();
        break;
      default:
        jj_la1[1] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      break;
    default:
      jj_la1[2] = jj_gen;
      ;
    }
  }

  final public void ExpressaoAritmeticaOuLogica() throws ParseException {
    Termo2();
    MenorPrioridade();
  }

  final public void MenorPrioridade() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case PLUS:
    case MINUS:
    case PIPE:
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case PLUS:
        jj_consume_token(PLUS);
        Termo2();
        MenorPrioridade();
        break;
      case MINUS:
        jj_consume_token(MINUS);
        Termo2();
        MenorPrioridade();
        break;
      case PIPE:
        jj_consume_token(PIPE);
        Termo2();
        MenorPrioridade();
        break;
      default:
        jj_la1[3] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      break;
    default:
      jj_la1[4] = jj_gen;
      ;
    }
  }

  final public void Termo2() throws ParseException {
    Termo1();
    MediaPrioridade();
  }

  final public void MediaPrioridade() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case STAR:
    case SLASH:
    case PERCENT:
    case DOUBLE_PERCENT:
    case AMPERSAND:
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case STAR:
        jj_consume_token(STAR);
        Termo1();
        MediaPrioridade();
        break;
      case SLASH:
        jj_consume_token(SLASH);
        Termo1();
        MediaPrioridade();
        break;
      case PERCENT:
        jj_consume_token(PERCENT);
        Termo1();
        MediaPrioridade();
        break;
      case DOUBLE_PERCENT:
        jj_consume_token(DOUBLE_PERCENT);
        Termo1();
        MediaPrioridade();
        break;
      case AMPERSAND:
        jj_consume_token(AMPERSAND);
        Termo1();
        MediaPrioridade();
        break;
      default:
        jj_la1[5] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      break;
    default:
      jj_la1[6] = jj_gen;
      ;
    }
  }

  final public void Termo1() throws ParseException {
    Elemento();
    MaiorPrioridade();
  }

  final public void MaiorPrioridade() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case POWER:
      jj_consume_token(POWER);
      Elemento();
      MaiorPrioridade();
      break;
    default:
      jj_la1[7] = jj_gen;
      ;
    }
  }

  final public void Elemento() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case IDENTIFIER:
      jj_consume_token(IDENTIFIER);
      break;
    case NUMBER:
      jj_consume_token(NUMBER);
      break;
    case REAL:
      jj_consume_token(REAL);
      break;
    case TEXT_DOUBLE:
      jj_consume_token(TEXT_DOUBLE);
      break;
    case TEXT_SINGLE:
      jj_consume_token(TEXT_SINGLE);
      break;
    case TRUE:
      jj_consume_token(TRUE);
      break;
    case FALSE:
      jj_consume_token(FALSE);
      break;
    case LPAREN:
      jj_consume_token(LPAREN);
      Expressao();
      jj_consume_token(RPAREN);
      break;
    case EXCLAMATION:
      jj_consume_token(EXCLAMATION);
      jj_consume_token(LPAREN);
      Expressao();
      jj_consume_token(RPAREN);
      break;
    default:
      jj_la1[8] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  final public void ListaDeElementos() throws ParseException {
    Elemento();
    ListaDeElementosAux();
  }

  final public void ListaDeElementosAux() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case COMMA:
      jj_consume_token(COMMA);
      ListaDeElementos();
      break;
    default:
      jj_la1[9] = jj_gen;
      ;
    }
  }

  final public void ListaIdentificadores() throws ParseException {
    jj_consume_token(IDENTIFIER);
    ListaIdentificadoresAux();
  }

  final public void ListaIdentificadoresAux() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case COMMA:
      jj_consume_token(COMMA);
      jj_consume_token(IDENTIFIER);
      ListaIdentificadores();
      break;
    default:
      jj_la1[10] = jj_gen;
      ;
    }
  }

  final public void Variavel() throws ParseException {
    ListaIdentificadores();
    jj_consume_token(COLON);
    DeclaracaoTipo();
    jj_consume_token(SEMICOLON);
  }

  final public void Tipo() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case TYPE_NUM:
      jj_consume_token(TYPE_NUM);
      break;
    case TYPE_REAL:
      jj_consume_token(TYPE_REAL);
      break;
    case TYPE_TEXT:
      jj_consume_token(TYPE_TEXT);
      break;
    case TYPE_FLAG:
      jj_consume_token(TYPE_FLAG);
      break;
    default:
      jj_la1[11] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  final public void DeclaracaoTipo() throws ParseException {
    Tipo();
    SufixoDoTipo();
  }

  final public void SufixoDoTipo() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case ASSIGN:
    case LBRACKET:
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case ASSIGN:
        jj_consume_token(ASSIGN);
        Elemento();
        break;
      case LBRACKET:
        DeclaracaoArray();
        break;
      default:
        jj_la1[12] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      break;
    default:
      jj_la1[13] = jj_gen;
      ;
    }
  }

  final public void DeclaracaoArray() throws ParseException {
    jj_consume_token(LBRACKET);
    jj_consume_token(NUMBER);
    jj_consume_token(RBRACKET);
    DeclaracaoValoresArray();
  }

  final public void DeclaracaoValoresArray() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case ASSIGN:
      jj_consume_token(ASSIGN);
      jj_consume_token(LBRACE);
      ListaDeElementos();
      jj_consume_token(RBRACE);
      break;
    default:
      jj_la1[14] = jj_gen;
      ;
    }
  }

  final public void ListaDeVariaveis() throws ParseException {
    Variavel();
    ListaDeVariaveisAux();
  }

  final public void ListaDeVariaveisAux() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case IDENTIFIER:
      ListaDeVariaveis();
      break;
    default:
      jj_la1[15] = jj_gen;
      ;
    }
  }

  final public void BlocoDefine() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case DEFINE:
      jj_consume_token(DEFINE);
      ListaDeVariaveis();
      break;
    default:
      jj_la1[16] = jj_gen;
      ;
    }
  }

  final public void Atribuicao() throws ParseException {
    jj_consume_token(SET);
    jj_consume_token(IDENTIFIER);
    SufixoDaAtribuicao();
    jj_consume_token(SEMICOLON);
  }

  final public void SufixoDaAtribuicao() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case ASSIGN:
      jj_consume_token(ASSIGN);
      Expressao();
      break;
    case LBRACKET:
      jj_consume_token(LBRACKET);
      Expressao();
      jj_consume_token(RBRACKET);
      jj_consume_token(ASSIGN);
      Expressao();
      break;
    default:
      jj_la1[17] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  final public void EntradaDeDados() throws ParseException {
    jj_consume_token(READ);
    jj_consume_token(LPAREN);
    jj_consume_token(IDENTIFIER);
    SufixoIdentificador();
    jj_consume_token(RPAREN);
    jj_consume_token(SEMICOLON);
  }

  final public void SufixoIdentificador() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case LBRACKET:
      jj_consume_token(LBRACKET);
      Expressao();
      jj_consume_token(RBRACKET);
      break;
    default:
      jj_la1[18] = jj_gen;
      ;
    }
  }

  final public void SaidaDeDados() throws ParseException {
    jj_consume_token(SHOW);
    jj_consume_token(LPAREN);
    ListaDeElementos();
    jj_consume_token(RPAREN);
    jj_consume_token(SEMICOLON);
  }

  final public void Selecao() throws ParseException {
    jj_consume_token(IF);
    Expressao();
    jj_consume_token(THEN);
    ListaDeComandos();
    Else();
    jj_consume_token(END);
    jj_consume_token(SEMICOLON);
  }

  final public void Else() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case ELSE:
      jj_consume_token(ELSE);
      ListaDeComandos();
      break;
    default:
      jj_la1[19] = jj_gen;
      ;
    }
  }

  final public void Repeticao() throws ParseException {
    jj_consume_token(LOOP);
    jj_consume_token(WHILE);
    Expressao();
    ListaDeComandos();
    jj_consume_token(END);
    jj_consume_token(SEMICOLON);
  }

  final public void Comando() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case SET:
      Atribuicao();
      break;
    case READ:
      EntradaDeDados();
      break;
    case SHOW:
      SaidaDeDados();
      break;
    case IF:
      Selecao();
      break;
    case LOOP:
      Repeticao();
      break;
    default:
      jj_la1[20] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  final public void ListaDeComandos() throws ParseException {
    Comando();
    ListaDeComandosAux();
  }

  final public void ListaDeComandosAux() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case SET:
    case READ:
    case SHOW:
    case IF:
    case LOOP:
      ListaDeComandos();
      break;
    default:
      jj_la1[21] = jj_gen;
      ;
    }
  }

  /** Generated Token Manager. */
  public Linguagem20252TokenManager token_source;
  SimpleCharStream jj_input_stream;
  /** Current token. */
  public Token token;
  /** Next token. */
  public Token jj_nt;
  private int jj_ntk;
  private int jj_gen;
  final private int[] jj_la1 = new int[22];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static {
      jj_la1_init_0();
      jj_la1_init_1();
   }
   private static void jj_la1_init_0() {
      jj_la1_0 = new int[] {0x0,0x60000,0x60000,0x60000000,0x60000000,0x80000000,0x80000000,0x0,0x8001d00,0x200000,0x200000,0x0,0x2010000,0x2010000,0x10000,0x0,0x0,0x2010000,0x2000000,0x0,0x0,0x0,};
   }
   private static void jj_la1_init_1() {
      jj_la1_1 = new int[] {0x40000000,0xf0,0xf0,0x200,0x200,0x40b,0x40b,0x4,0x58000100,0x0,0x0,0x7800,0x0,0x0,0x0,0x40000000,0x10000,0x0,0x0,0x1000000,0x2780000,0x2780000,};
   }

  /** Constructor with InputStream. */
  public Linguagem20252(java.io.InputStream stream) {
     this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public Linguagem20252(java.io.InputStream stream, String encoding) {
    try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source = new Linguagem20252TokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 22; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream) {
     ReInit(stream, null);
  }
  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream, String encoding) {
    try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 22; i++) jj_la1[i] = -1;
  }

  /** Constructor. */
  public Linguagem20252(java.io.Reader stream) {
    jj_input_stream = new SimpleCharStream(stream, 1, 1);
    token_source = new Linguagem20252TokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 22; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(java.io.Reader stream) {
    jj_input_stream.ReInit(stream, 1, 1);
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 22; i++) jj_la1[i] = -1;
  }

  /** Constructor with generated Token Manager. */
  public Linguagem20252(Linguagem20252TokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 22; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(Linguagem20252TokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 22; i++) jj_la1[i] = -1;
  }

  private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }


/** Get the next Token. */
  final public Token getNextToken() {
    if (token.next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    jj_gen++;
    return token;
  }

/** Get the specific Token. */
  final public Token getToken(int index) {
    Token t = token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) t = t.next;
      else t = t.next = token_source.getNextToken();
    }
    return t;
  }

  private int jj_ntk() {
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  private java.util.List jj_expentries = new java.util.ArrayList();
  private int[] jj_expentry;
  private int jj_kind = -1;

  /** Generate ParseException. */
  public ParseException generateParseException() {
    jj_expentries.clear();
    boolean[] la1tokens = new boolean[64];
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 22; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
          if ((jj_la1_1[i] & (1<<j)) != 0) {
            la1tokens[32+j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 64; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.add(jj_expentry);
      }
    }
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = (int[])jj_expentries.get(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  /** Enable tracing. */
  final public void enable_tracing() {
  }

  /** Disable tracing. */
  final public void disable_tracing() {
  }

}
