/* Generated By:JavaCC: Do not edit this line. Linguagem20252Constants.java */
package app;
/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface Linguagem20252Constants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int BLANK_SPACE = 1;
  /** RegularExpression Id. */
  int END_OF_LINE = 2;
  /** RegularExpression Id. */
  int NEW_LINE = 3;
  /** RegularExpression Id. */
  int TABULATION = 4;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 5;
  /** RegularExpression Id. */
  int BLOCK_COMMENT = 6;
  /** RegularExpression Id. */
  int NUMBER = 7;
  /** RegularExpression Id. */
  int REAL = 8;
  /** RegularExpression Id. */
  int LETTER = 9;
  /** RegularExpression Id. */
  int TEXT = 10;
  /** RegularExpression Id. */
  int ASSIGN = 11;
  /** RegularExpression Id. */
  int EQUAL = 12;
  /** RegularExpression Id. */
  int NOT_EQUAL = 13;
  /** RegularExpression Id. */
  int SEMICOLON = 14;
  /** RegularExpression Id. */
  int COLON = 15;
  /** RegularExpression Id. */
  int COMMA = 16;
  /** RegularExpression Id. */
  int DOT = 17;
  /** RegularExpression Id. */
  int LBRACE = 18;
  /** RegularExpression Id. */
  int RBRACE = 19;
  /** RegularExpression Id. */
  int LBRACKET = 20;
  /** RegularExpression Id. */
  int RBRACKET = 21;
  /** RegularExpression Id. */
  int LPAREN = 22;
  /** RegularExpression Id. */
  int RPAREN = 23;
  /** RegularExpression Id. */
  int PLUS = 24;
  /** RegularExpression Id. */
  int MINUS = 25;
  /** RegularExpression Id. */
  int STAR = 26;
  /** RegularExpression Id. */
  int SLASH = 27;
  /** RegularExpression Id. */
  int PERCENT = 28;
  /** RegularExpression Id. */
  int POWER = 29;
  /** RegularExpression Id. */
  int DOUBLE_PERCENT = 30;
  /** RegularExpression Id. */
  int SHIFT_LEFT = 31;
  /** RegularExpression Id. */
  int SHIFT_RIGHT = 32;
  /** RegularExpression Id. */
  int SHIFT_LEFT_ASSIGN = 33;
  /** RegularExpression Id. */
  int SHIFT_RIGHT_ASSIGN = 34;
  /** RegularExpression Id. */
  int EXCLAMATION = 35;
  /** RegularExpression Id. */
  int PIPE = 36;
  /** RegularExpression Id. */
  int AMPERSAND = 37;
  /** RegularExpression Id. */
  int TYPE_NUM = 38;
  /** RegularExpression Id. */
  int TYPE_REAL = 39;
  /** RegularExpression Id. */
  int TYPE_TEXT = 40;
  /** RegularExpression Id. */
  int TYPE_FLAG = 41;
  /** RegularExpression Id. */
  int BEGIN = 42;
  /** RegularExpression Id. */
  int DEFINE = 43;
  /** RegularExpression Id. */
  int START = 44;
  /** RegularExpression Id. */
  int END = 45;
  /** RegularExpression Id. */
  int SET = 46;
  /** RegularExpression Id. */
  int READ = 47;
  /** RegularExpression Id. */
  int SHOW = 48;
  /** RegularExpression Id. */
  int IF = 49;
  /** RegularExpression Id. */
  int THEN = 50;
  /** RegularExpression Id. */
  int ELSE = 51;
  /** RegularExpression Id. */
  int LOOP = 52;
  /** RegularExpression Id. */
  int WHILE = 53;
  /** RegularExpression Id. */
  int TRUE = 54;
  /** RegularExpression Id. */
  int FALSE = 55;
  /** RegularExpression Id. */
  int IDENTIFIER = 56;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\t\"",
    "<SINGLE_LINE_COMMENT>",
    "<BLOCK_COMMENT>",
    "<NUMBER>",
    "<REAL>",
    "<LETTER>",
    "<TEXT>",
    "\"=\"",
    "\"==\"",
    "\"!=\"",
    "\";\"",
    "\":\"",
    "\",\"",
    "\".\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\"(\"",
    "\")\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"**\"",
    "\"%%\"",
    "\"<<\"",
    "\">>\"",
    "\"<<=\"",
    "\">>=\"",
    "\"!\"",
    "\"|\"",
    "\"&\"",
    "\"num\"",
    "\"real\"",
    "\"text\"",
    "\"flag\"",
    "\"begin\"",
    "\"define\"",
    "\"start\"",
    "\"end\"",
    "\"set\"",
    "\"read\"",
    "\"show\"",
    "\"if\"",
    "\"then\"",
    "\"else\"",
    "\"loop\"",
    "\"while\"",
    "\"true\"",
    "\"false\"",
    "<IDENTIFIER>",
  };

}
